##############################################################
#
# This file includes all the test targets as well as all the
# non-default build rules and test recipes.
#
##############################################################


##############################################################
#
# Test targets
#
##############################################################

###### Place all generic definitions here ######

# This defines tests which run tools of the same name.  This is simply for convenience to avoid
# defining the test name twice (once in TOOL_ROOTS and again in TEST_ROOTS).
# Tests defined here should not be defined in TOOL_ROOTS and TEST_ROOTS.
TEST_TOOL_ROOTS :=

# This defines the tests to be run that were not already defined in TEST_TOOL_ROOTS.
TEST_ROOTS :=

# This defines a list of tests that should run in the "short" sanity. Tests in this list must also
# If the entire directory should be tested in sanity, assign TEST_TOOL_ROOTS and TEST_ROOTS to the
# SANITY_SUBSET variable in the tests section below (see example in makefile.rules.tmpl).
SANITY_SUBSET :=

# This defines the tools which will be run during the the tests, and were not already defined in
# TEST_TOOL_ROOTS.
TOOL_ROOTS :=

# This defines the static analysis tools which will be run during the the tests. They should not
# be defined in TEST_TOOL_ROOTS. If a test with the same name exists, it should be defined in
# TEST_ROOTS.
# Note: Static analysis tools are in fact executables linked with the Pin Static Analysis Library.
# This library provides a subset of the Pin APIs which allows the tool to perform static analysis
# of an application or dll. Pin itself is not used when this tool runs.
SA_TOOL_ROOTS :=

# This defines all the applications that will be run during the tests.
APP_ROOTS :=

# This defines any additional object files that need to be compiled.
OBJECT_ROOTS :=

# This defines any additional dlls (shared objects), other than the pintools, that need to be compiled.
DLL_ROOTS :=

# This defines any static libraries (archives), that need to be built.
LIB_ROOTS :=


##############################################################
#
# Test recipes
#
##############################################################

# This section contains recipes for tests other than the default.
# See makefile.default.rules for the default test rules.
# All tests in this section should adhere to the naming convention: <testname>.test


##############################################################
#
# Build rules
#
##############################################################

# See makefile.default.rules for the default build rules.

ARCH_QUERY = $(shell uname -m)
ifeq ($(ARCH_QUERY),i686)
	TARGET_ARCH = -DTARGET_IA32
else
	ifeq ($(ARCH_QUERY),x86_64)
		TARGET_ARCH ?= -DTARGET_INTEL64
	else
		$(error Unknown target arch: $(ARCH_QUERY))
	endif
endif

ROOT_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

TOOL_CXXFLAGS := -I$(SDE_ROOT)/include -I./sift $(TOOL_CXXFLAGS)
TOOL_CXXFLAGS += -DSDE_INIT# -DPINPLAY -I$(PINPLAY_ROOT)/include
TOOL_CXXFLAGS += -DPIN_RT -D_LIBCPP_HAS_MUSL_LIBC -DPIN_DISABLE_CRT_REG_DEF
TOOL_CXXFLAGS += -Wno-sign-compare
ifeq ($(OS),Windows_NT)
TOOL_CXXFLAGS += -D_GNU_SOURCE -D_XOPEN_SOURCE=700 -D_LIBCPP_NO_VCRUNTIME -D_LIBCPP_DISABLE_AVAILABILITY -D_mm_malloc
TOOL_CXXFLAGS += -nostdinc /std:c++17 -fno-builtin -Wno-unicode
TOOL_CXXFLAGS += -Wno-unknown-pragmas -Wno-pointer-sign -Wno-incompatible-pointer-types -Wno-microsoft-include
TOOL_CXXFLAGS += -Wno-ignored-attributes -Wno-unused-function -Wno-non-c-typedef-for-linkage
TOOL_CXXFLAGS += -Wno-invalid-noreturn -Wno-missing-braces -Wno-unused-command-line-argument
TOOL_CXXFLAGS += -Wno-nonportable-include-path -Wno-sizeof-pointer-memaccess -Wno-unused-value
TOOL_CXXFLAGS += -Wno-overloaded-virtual -Wno-unused-private-field -Wno-deprecated-declarations
TOOL_CXXFLAGS += -Wno-microsoft-enum-forward-reference -Wno-unused-but-set-variable -Wno-bitwise-instead-of-logical
TOOL_CXXFLAGS += -Wno-int-to-void-pointer-cast -Wno-inconsistent-missing-override
TOOL_CXXFLAGS += -mcx16
endif

ifeq ($(OS),Windows_NT)
TOOL_LPATHS += /LIBPATH:$(SDE_ROOT)/lib/$(TARGET) /LIBPATH:$(PINPLAY_ROOT)/$(TARGET)
TOOL_LPATHS += libpinplay.lib libsde.lib bz2.lib zlib.lib
else
# sde and pinplay libraries appears twice to avoid circular dependency
TOOL_LPATHS += -L$(SDE_ROOT)/lib/$(TARGET) -L$(PINPLAY_ROOT)/$(TARGET)
TOOL_LPATHS += -lpinplay -lsde -lpinplay -lsde -lbz2 -lzlib
endif


PINPLAY_HOME = $(PIN_ROOT)/extras/pinplay
PINPLAY_INCLUDE_HOME = $(PINPLAY_HOME)/include
PINPLAY_LIB_HOME = $(PINPLAY_HOME)/lib/$(TARGET)

ifneq ($(wildcard $(PINPLAY_HOME)/include/pinplay.H),)
EXT_LIB_HOME = $(PINPLAY_HOME)/lib-ext/$(TARGET)
PINPLAY_CXXFLAGS = -DPINPLAY -D_FILE_OFFSET_BITS=64 -I$(PINPLAY_INCLUDE_HOME)
PINPLAY_LIBS = $(PINPLAY_LIB_HOME)/libpinplay.a $(EXT_LIB_HOME)/libbz2.a $(EXT_LIB_HOME)/libzlib.a
PINPLAY_LD_FLAGS = -L$(PINPLAY_LIB_HOME) -L$(EXT_LIB_HOME)
else
PINPLAY_CXXFLAGS =
PINPLAY_LIBS =
PINPLAY_LD_FLAGS =
endif

ifneq ($(DEBUG_SHOW_COMPILE),)
  SHOW_COMPILE=1
  MAKE_QUIET=
  _MSG=@echo >/dev/null
  _CMD=
else
  SHOW_COMPILE=
  MAKE_QUIET=--quiet
  _MSG=@echo
  _CMD=@
endif



COMPILE_PIN_FLAGS := -g -std=c++1z $(PINPLAY_CXXFLAGS) $(TOOL_CXXFLAGS)
LINK_FLAGS := -g $(TOOL_LDFLAGS)
	
LINK_LIBS = sift/libsift.a $(PINPLAY_LIBS)

SOURCES=$(wildcard *.cc) $(wildcard ../bbv_count.cc)
OBJECTS=$(patsubst %.cc,$(OBJDIR)%$(OBJ_SUFFIX),$(SOURCES))

export PINPLAY_INCLUDE_HOME
export COMPILE_PIN_FLAGS

all: sift/libsift.a $(OBJDIR)pin_frontend

$(OBJDIR)%$(OBJ_SUFFIX) : %.cc $(wildcard *.h) $(wildcard ../*.h) $(wildcard ../*.tcc)
	$(_MSG) '[CXX   ]' $(subst $(shell readlink -f $(ROOT_DIR)/../../)/,,$(shell readlink -f $@))
	$(_CMD) $(TOOL_CXX) $(COMPILE_PIN_FLAGS) -I$(ROOT_DIR)/sift -I$(ROOT_DIR)/.. $(TARGET_ARCH) -c -o $@ $< $(CXXFLAGS)

sift/sift_reader.h: sift
	@for i in $(wildcard $(ROOT_DIR)/../../sift/*.h) $(wildcard $(ROOT_DIR)/../../sift/*.cc) ; do ln -fs $$i sift/. ; done
	@ln -fs $(ROOT_DIR)/../../common/misc/fixed_types.h sift/.

# Build libsift against PinCRT
sift/libsift.a: sift/sift_reader.h $(wildcard sift/*.h) $(wildcard sift/*.cc)
	$(MAKE) -C sift
ifneq ($(strip $(CONTROLLERLIB)),)
  # Only add the controller lib if its directory tree actually exists
  ifneq (,$(wildcard $(shell dirname $(shell dirname $(CONTROLLERLIB)))))
    FRONTEND_DEPS := $(CONTROLLERLIB)
  endif
endif

$(OBJDIR)pin_frontend: $(OBJECTS) $(LINK_LIBS) $(FRONTEND_DEPS)
	$(_MSG) '[LD    ]' $(subst $(shell readlink -f $(ROOT_DIR)/../../)/,,$(shell readlink -f $@))
	$(_CMD) $(TOOL_LINKER) $(LINK_FLAGS) $(LINK_EXE) $@ $(^:%.h=) $(TOOL_LPATHS) $(TOOL_LIBS)

clean: cleanall

cleanall:
	#$(_MSG) '[CLEAN ]' $(subst $(shell readlink -f $(ROOT_DIR)/../..)/,,$(shell readlink -f $(ROOT_DIR)))
	$(_CMD) rm -f *.o
	$(MAKE) -C sift clean

